"""moz_openscad 的类型存根（PEP 561）。

模块名是 ``moz_openscad``（顶层模块，不是包），所以存根文件名是 ``moz_openscad.pyi``。
注意：把它随 wheel 一起分发还需要打包工作（见 docs/roadmap.md §1）。
"""

from array import array as _array
from collections.abc import Callable, Sequence
from typing import Any, Union

__all__: list[str]

# SCAD 侧能接受的对象：Shape 或一段 SCAD 源码
# （用字符串前向引用：别名的定义位置在 Shape 之前）
ShapeLike = Union["Shape", str]

class OpenSCADError(RuntimeError): ...

class Measure:
    """``Geometry.measure`` 的结果快照。"""
    dimension: int
    is_empty: bool
    bbox_min: tuple[float, float, float]
    bbox_max: tuple[float, float, float]
    volume: float
    area: float
    facets: int
    vertices: int
    centroid: tuple[float, float, float]
    @property
    def bbox(self) -> tuple[tuple[float, float, float], tuple[float, float, float]]: ...

class RenderOptions:
    """``moz_render_options`` 的镜像。"""
    width: int
    height: int
    renderer: int
    show_faces: int
    show_edges: int
    show_axes: int
    show_scales: int
    show_crosshairs: int
    colorscheme: bytes | None

class Geometry:
    """一次解析 + 求值的产物句柄。"""
    def __init__(self, handle: Any, borrowed: bool = ...) -> None: ...
    @property
    def dimension(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def measure(self) -> Measure: ...
    @property
    def log(self) -> str: ...
    def take_log(self) -> str: ...
    def export(
        self, fmt: str, path: str, *,
        source_file_name: str | None = ..., source_file_path: str | None = ...,
    ) -> None: ...
    def export_bytes(
        self, fmt: str, *,
        source_file_name: str | None = ..., source_file_path: str | None = ...,
    ) -> bytes: ...
    def face_colors(self, colorscheme: str | None = ...) -> bytes: ...
    def triangles(self) -> _array: ...
    def contains_point(self, x: float, y: float, z: float) -> bool: ...
    def distance_to_surface(self, x: float, y: float, z: float) -> float: ...
    def inertia(
        self,
    ) -> tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]]: ...
    def render_png(self, path: str, width: int = ..., height: int = ..., **options: Any) -> None: ...
    def render_png_bytes(self, width: int = ..., height: int = ..., **options: Any) -> bytes: ...
    def show(self, title: str = ..., width: int = ..., height: int = ...) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Geometry: ...
    def __exit__(self, *exc: Any) -> None: ...

class Shape:
    """Python 侧拼出来的 SCAD 源码（求值推迟到访问属性时，且有惰性缓存）。"""
    source: str
    variables: dict[str, Any]
    def __init__(self, source: str, **variables: Any) -> None: ...
    @property
    def dimension(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def measure(self) -> Measure: ...
    @property
    def log(self) -> str: ...
    def eval(self, **variables: Any) -> Geometry: ...
    def export(self, fmt: str, path: str, **options: Any) -> None: ...
    def export_bytes(self, fmt: str, **options: Any) -> bytes: ...
    def face_colors(self, colorscheme: str | None = ...) -> bytes: ...
    def triangles(self) -> _array: ...
    def contains_point(self, x: float, y: float, z: float) -> bool: ...
    def distance_to_surface(self, x: float, y: float, z: float) -> float: ...
    def inertia(
        self,
    ) -> tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]]: ...
    def render_png(self, path: str, width: int = ..., height: int = ..., **options: Any) -> None: ...
    def render_png_bytes(self, width: int = ..., height: int = ..., **options: Any) -> bytes: ...
    def show(self, title: str = ..., width: int = ..., height: int = ...) -> None: ...
    # 布尔
    def union(self, *others: ShapeLike) -> Shape: ...
    def difference(self, *others: ShapeLike) -> Shape: ...
    def intersection(self, *others: ShapeLike) -> Shape: ...
    def hull(self, *others: ShapeLike) -> Shape: ...
    def minkowski(self, *others: ShapeLike) -> Shape: ...
    def add(self, *others: ShapeLike) -> Shape: ...
    def cut(self, *others: ShapeLike) -> Shape: ...
    # 变换
    def translate(self, vector: Sequence[float]) -> Shape: ...
    def rotate(self, a: Any, v: Any = ...) -> Shape: ...
    def scale(self, vector: Sequence[float]) -> Shape: ...
    def mirror(self, vector: Sequence[float]) -> Shape: ...
    def resize(self, newsize: Sequence[float], auto: Any = ...) -> Shape: ...
    def linear_extrude(
        self, height: float, center: bool = ..., scale: Any = ..., twist: Any = ...,
        slices: int | None = ..., convexity: int | None = ...,
        fn: int | None = ..., fa: float | None = ..., fs: float | None = ...,
    ) -> Shape: ...
    def rotate_extrude(
        self, angle: float = ..., convexity: int | None = ...,
        fn: int | None = ..., fa: float | None = ..., fs: float | None = ...,
    ) -> Shape: ...
    def offset(
        self, r: float | None = ..., delta: float | None = ..., chamfer: bool | None = ...,
        fn: int | None = ..., fa: float | None = ..., fs: float | None = ...,
    ) -> Shape: ...
    def projection(self, cut: bool = ...) -> Shape: ...
    def color(self, name: Any, alpha: float | None = ...) -> Shape: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Part:
    """更面向对象的一层包装，最终落回 Shape。"""
    shape: Shape
    name: str | None
    def __init__(self, shape: Shape | Part | str, name: str | None = ...) -> None: ...
    @property
    def source(self) -> str: ...
    @property
    def dimension(self) -> int: ...
    @property
    def measure(self) -> Measure: ...
    def export(self, fmt: str, path: str, **options: Any) -> None: ...
    def export_bytes(self, fmt: str, **options: Any) -> bytes: ...
    def face_colors(self, colorscheme: str | None = ...) -> bytes: ...
    def triangles(self) -> _array: ...
    def contains_point(self, x: float, y: float, z: float) -> bool: ...
    def distance_to_surface(self, x: float, y: float, z: float) -> float: ...
    def inertia(
        self,
    ) -> tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float]]: ...
    def render_png(self, path: str, width: int = ..., height: int = ..., **options: Any) -> None: ...
    def render_png_bytes(self, width: int = ..., height: int = ..., **options: Any) -> bytes: ...
    def show(self, title: str = ..., width: int = ..., height: int = ...) -> None: ...
    def at(self, x: float = ..., y: float = ..., z: float = ...) -> Part: ...
    def move(self, vector: Sequence[float]) -> Part: ...
    def rotate(self, a: Any, v: Any = ...) -> Part: ...
    def scale(self, vector: Sequence[float]) -> Part: ...
    def mirror(self, vector: Sequence[float]) -> Part: ...
    def add(self, *others: Part | Shape | str) -> Part: ...
    def cut(self, *others: Part | Shape | str) -> Part: ...
    def __add__(self, other: Part | Shape | str) -> Part: ...
    def __sub__(self, other: Part | Shape | str) -> Part: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Box(Part): ...
class Cylinder(Part): ...
class Sphere(Part): ...
class Hole(Part): ...
class Plate(Part): ...
class Bracket(Part): ...

# --- 求值 / 导出 / 取值 ---
def eval_text(source: str, **variables: Any) -> Geometry: ...
def eval_file(path: str, **variables: Any) -> Geometry: ...
def dump(source: str, fmt: str = ..., *, docname: str | None = ..., **variables: Any) -> str: ...
def dump_file(path: str, fmt: str = ..., **variables: Any) -> str: ...
def value(expression: str, source: str = ..., **variables: Any) -> str: ...
def number(expression: str, source: str = ..., **variables: Any) -> float: ...
def vector(expression: str, source: str = ..., **variables: Any) -> list[Any]: ...

# --- 动画 / 库路径 / 预览 ---
def eval_animation(
    source: str, frames: int, fps: float = ...,
    *, callback: Callable[[int, Geometry], Any], path: str | None = ..., **variables: Any,
) -> int: ...
def add_library_path(path: str) -> None: ...
def library_paths() -> list[str]: ...
def show_animation(
    frame_fn: Callable[[int], Shape], frames: int, fps: float = ...,
    title: str = ..., width: int = ..., height: int = ...,
) -> None: ...
def show_parts(
    parts: Sequence[tuple[str, ShapeLike]] | dict[str, ShapeLike],
    title: str = ..., width: int = ..., height: int = ...,
) -> None: ...

# --- 形状原语 ---
def cube(size: Any = ..., center: bool = ...) -> Shape: ...
def sphere(r: float = ..., d: float | None = ..., fn: int | None = ..., fa: float | None = ..., fs: float | None = ...) -> Shape: ...
def cylinder(
    h: float = ..., r: float | None = ..., r1: float | None = ..., r2: float | None = ...,
    d: float | None = ..., d1: float | None = ..., d2: float | None = ..., center: bool = ...,
    fn: int | None = ..., fa: float | None = ..., fs: float | None = ...,
) -> Shape: ...
def circle(r: float = ..., d: float | None = ..., fn: int | None = ..., fa: float | None = ..., fs: float | None = ...) -> Shape: ...
def square(size: Any = ..., center: bool = ...) -> Shape: ...
def polygon(points: Any, paths: Any = ...) -> Shape: ...
def text(
    value: str, size: float = ..., font: str | None = ..., halign: str | None = ...,
    valign: str | None = ..., spacing: float = ..., direction: str | None = ...,
    fn: int | None = ..., fa: float | None = ..., fs: float | None = ...,
) -> Shape: ...
def polyhedron(points: Any, faces: Any = ..., triangles: Any = ..., convexity: int | None = ...) -> Shape: ...
def import_shape(file: str, layer: str | None = ..., origin: Any = ..., scale: float | None = ..., convexity: int | None = ...) -> Shape: ...
def surface(file: str, center: bool = ..., convexity: int | None = ..., invert: bool = ...) -> Shape: ...

# --- 布尔 / 变换 / 修饰符 ---
def union(*items: ShapeLike) -> Shape: ...
def difference(*items: ShapeLike) -> Shape: ...
def intersection(*items: ShapeLike) -> Shape: ...
def hull(*items: ShapeLike) -> Shape: ...
def minkowski(*items: ShapeLike) -> Shape: ...
def translate(vector: Sequence[float], obj: ShapeLike | None = ...) -> Shape: ...
def rotate(a: Any, v: Any = ..., obj: ShapeLike | None = ...) -> Shape: ...
def scale(vector: Sequence[float], obj: ShapeLike | None = ...) -> Shape: ...
def mirror(vector: Sequence[float], obj: ShapeLike | None = ...) -> Shape: ...
def resize(newsize: Sequence[float], obj: ShapeLike | None = ..., auto: Any = ...) -> Shape: ...
def multmatrix(matrix: Any, obj: ShapeLike | None = ...) -> Shape: ...
def background(obj: ShapeLike | None = ...) -> Shape: ...
def highlight(obj: ShapeLike | None = ...) -> Shape: ...
def only(obj: ShapeLike | None = ...) -> Shape: ...
def disable(obj: ShapeLike | None = ...) -> Shape: ...
def linear_extrude(
    obj: ShapeLike, height: float, center: bool = ..., scale: Any = ..., twist: Any = ...,
    slices: int | None = ..., convexity: int | None = ...,
    fn: int | None = ..., fa: float | None = ..., fs: float | None = ...,
) -> Shape: ...
def rotate_extrude(obj: ShapeLike, angle: float = ..., convexity: int | None = ..., fn: int | None = ..., fa: float | None = ..., fs: float | None = ...) -> Shape: ...
def offset(obj: ShapeLike, r: float | None = ..., delta: float | None = ..., chamfer: bool | None = ..., fn: int | None = ..., fa: float | None = ..., fs: float | None = ...) -> Shape: ...
def projection(obj: ShapeLike, cut: bool = ...) -> Shape: ...
def color(obj: ShapeLike, name: Any, alpha: float | None = ...) -> Shape: ...
def settings(obj: ShapeLike, **variables: Any) -> Shape: ...

# --- 与 SCAD 逐比特一致的取值助手 ---
def lookup(key: float, pairs: Sequence[Sequence[float]]) -> float | None: ...
def sin_deg(x: float) -> float: ...
def cos_deg(x: float) -> float: ...
def tan_deg(x: float) -> float: ...
def asin_deg(x: float) -> float: ...
def acos_deg(x: float) -> float: ...
def atan_deg(x: float) -> float: ...
def atan2_deg(y: float, x: float) -> float: ...

RENDERER_OPENCSG: int
RENDERER_THROWNTOGETHER: int
RENDERER_CGAL: int
